export default {
//  GET_ALL_REVIEWS: Symbol('GET_ALL_REVIEWS'),
  INIT_STORE: Symbol('INIT_STORE'),
  START_REVIEWING: Symbol('START_REVIEWING'),
  QUIT_REVIEWING: Symbol('QUIT_REVIEWING'),
  POST_NEW_REVIEW: Symbol('POST_NEW_REVIEW'),
  POST_NEW_WHISKY_WITH_REVIEW: Symbol('POST_NEW_WHISKY_WITH_REVIEW'),
}
