export default {
  STORE_INITED: Symbol('STORE_INITED'),
  TARGET_WHISKY_SET: Symbol('TARGET_WHISKY_SET'),
  TARGET_WHISKY_REMOVED: Symbol('TARGET_WHISKY_REMOVED'),
  BACK_BUTTON_SET: Symbol('BACK_BUTTON_SET'),
  URL_SAVED: Symbol('URL_SAVED'),
  REVIEWING_ENTERED: Symbol('REVIEWING_ENTERED'),
  REVIEWING_EXITED: Symbol('REVIEWING_EXITED'),
  REVIEWS_UPDATED: Symbol('REVIEWS_UPDATED'),
  WHISKY_AND_REVIEW_UPDATED: Symbol('WHISKY_AND_REVIEW_UPDATED'),
}
