export default {
  STORE_INITED: Symbol('STORE_INITED'),
  TARGET_WHISKY_SET: Symbol('TARGET_WHISKY_SET'),
  TARGET_WHISKY_REMOVED: Symbol('TARGET_WHISKY_REMOVED'),
  REVIEWING_READY: Symbol('REVIEWING_READY'),
  REVIEWING_QUITED: Symbol('REVIEWING_QUITED'),
  REVIEWS_UPDATED: Symbol('REVIEWS_UPDATED'),
  WHISKY_AND_REVIEW_UPDATED: Symbol('WHISKY_AND_REVIEW_UPDATED'),
}
