export default {
  STORE_INITED: Symbol('STORE_INITED'),
  REVIEWING_READY: Symbol('REVIEWING_READY'),
  REVIEWS_UPDATED: Symbol('REVIEWS_UPDATED'),
  WHISKY_AND_REVIEW_UPDATED: Symbol('REVIEWS_UPDATED'),
}
